import {
  WorkerOptions,
  cli,
  defineAgent,
  multimodal,
} from "@livekit/agents";
import * as openai from "@livekit/agents-plugin-openai";
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";

dotenv.config();

const LIVEKIT_URL = process.env.LIVEKIT_URL;
const LIVEKIT_API_KEY = process.env.LIVEKIT_API_KEY;
const LIVEKIT_API_SECRET = process.env.LIVEKIT_API_SECRET;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE = process.env.SUPABASE_SECRET_KEY;

if (!LIVEKIT_URL || !LIVEKIT_API_KEY || !LIVEKIT_API_SECRET) {
  console.error("❌ Missing LiveKit environment variables");
  process.exit(1);
}

if (!OPENAI_API_KEY) {
  console.error("❌ Missing OPENAI_API_KEY");
  process.exit(1);
}

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE) {
  console.error("❌ Missing Supabase environment variables");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE);

/**
 * LiveKit Agents voice worker
 *
 * When a user joins a LiveKit room from the Flutter app:
 * 1. This agent automatically joins the same room
 * 2. Fetches call context (instructions) from Supabase
 * 3. Starts a voice conversation using OpenAI Realtime
 * 4. Saves transcript when call ends
 */
const agent = defineAgent({
  entry: async (ctx) => {
    console.log(`🟢 Agent entry for room: ${ctx.room.name}`);

    // Wait for the user to connect
    const participant = await ctx.waitForParticipant();
    console.log(`👤 Participant joined: ${participant.identity}`);

    // Get room name to fetch context from Supabase
    const roomName = ctx.room.name;

    // Fetch instructions from call_context table
    const { data: context, error } = await supabase
      .from("call_context")
      .select("instructions, user_id, call_type")
      .eq("room_name", roomName)
      .single();

    if (error) {
      console.error("❌ Failed to fetch call context:", error);
    }

    const instructions = context?.instructions || getDefaultInstructions();
    const userId = context?.user_id;
    const callType = context?.call_type;

    console.log(`📋 Call type: ${callType}, User: ${userId}`);

    // Create multimodal agent with OpenAI Realtime
    const assistant = new multimodal.MultimodalAgent({
      model: new openai.realtime.RealtimeModel({
        instructions,
        voice: "verse", // calm, warm voice
        turnDetection: {
          type: "server_vad",
          threshold: 0.5,
          silenceDurationMs: 500,
          prefixPaddingMs: 300,
        },
        modalities: ["audio", "text"],
      }),
    });

    // Track conversation for transcript
    const transcript: Array<{ role: string; content: string; timestamp: Date }> = [];

    // Start the assistant
    const session = await assistant.start(ctx.room, participant);
    console.log("🤖 Voice assistant started");

    // Handle user speech transcription
    session.on("user_speech_committed", (text: string) => {
      console.log(`👤 User: ${text}`);
      transcript.push({ role: "user", content: text, timestamp: new Date() });
    });

    // Handle assistant speech
    session.on("agent_speech_committed", (text: string) => {
      console.log(`🤖 Kai: ${text}`);
      transcript.push({ role: "assistant", content: text, timestamp: new Date() });
    });

    // Wait for disconnect
    await ctx.waitForDisconnect();
    console.log(`🔴 Call ended for room: ${roomName}`);

    // Save session to Supabase
    if (userId && transcript.length > 0) {
      try {
        await saveSession(userId, callType, transcript);
        console.log("💾 Session saved");
      } catch (err) {
        console.error("❌ Failed to save session:", err);
      }
    }

    // Clean up call context
    if (roomName) {
      await supabase
        .from("call_context")
        .delete()
        .eq("room_name", roomName);
    }
  },
});

/**
 * Save the session transcript to Supabase
 */
async function saveSession(
  userId: string,
  callType: string | undefined,
  transcript: Array<{ role: string; content: string; timestamp: Date }>
) {
  const transcriptText = transcript
    .map((t) => `${t.role === "user" ? "User" : "Kai"}: ${t.content}`)
    .join("\n\n");

  await supabase.from("sessions").insert({
    user_id: userId,
    session_type: callType || "on_demand",
    transcript: transcriptText,
    started_at: transcript[0]?.timestamp.toISOString(),
    ended_at: transcript[transcript.length - 1]?.timestamp.toISOString(),
    // summary will be generated by analytics engine later
  });
}

/**
 * Default instructions if context not found
 */
function getDefaultInstructions(): string {
  return `You are Kai, a supportive and calm voice coach.

Your role is to help the user reflect through gentle conversation.
You are NOT a therapist. You're a supportive companion.

## Tone
- Warm and calm
- Non-judgmental
- Brief responses (1-2 sentences)

## Flow
1. Greet them warmly
2. Ask what's on their mind
3. Listen and reflect back
4. End when they feel heard

Keep it conversational, not clinical.`;
}

// Run the agent
cli.runApp(
  new WorkerOptions({
    agent,
  })
);
